on: [push]

name: specs

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Set up Ruby
        uses: ruby/setup-ruby@master
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec
